spring:
  datasource:
    #配置阿里巴巴数据源的四大件
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://61.183.139.103:8082/hris_db?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      #配置连接池的详细信息
      initialSize: 1
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL

server:
  #修改服务器端口号
  port: 8901

#配置pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#配置mybatis
mybatis:
  type-aliases-package: cn.com.djin.springboot.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启MyBatis的二级缓存
    cache-enabled: true
    #开启懒加载
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false
  mapper-locations: classpath:mapper/*.xml
      